# Generated by Django 6.0.3 on 2026-04-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('grau', models.CharField(max_length=100)),
                ('area_cientifica', models.CharField(max_length=150)),
                ('duracao', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='licenciaturas/')),
            ],
        ),
    ]
