# Generated by Django 6.0.3 on 2026-04-03 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_competencia_docente_empresaparceira_formacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadecurricular',
            name='licenciatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ucs', to='portfolio.licenciatura'),
            preserve_default=False,
        ),
    ]
