# Generated by Django 6.0.3 on 2026-04-03 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_unidadecurricular_licenciatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='unidade_curricular',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='portfolio.unidadecurricular'),
            preserve_default=False,
        ),
    ]
