# Generated by Django 6.0.3 on 2026-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projeto_unidade_curricular'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadecurricular',
            name='docentes',
            field=models.ManyToManyField(related_name='unidades_curriculares', to='portfolio.docente'),
        ),
    ]
