# Generated by Django 6.0.3 on 2026-04-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_unidadecurricular_docentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(related_name='projetos', to='portfolio.tecnologia'),
        ),
        migrations.AlterField(
            model_name='unidadecurricular',
            name='docentes',
            field=models.ManyToManyField(related_name='ucs', to='portfolio.docente'),
        ),
    ]
