# Generated by Django 6.0.3 on 2026-04-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_projeto_tecnologias_alter_unidadecurricular_docentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='competencia',
            field=models.ManyToManyField(related_name='projetos', to='portfolio.competencia'),
        ),
    ]
