# Generated by Django 6.0.3 on 2026-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projeto_competencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='competencia',
            new_name='competencias',
        ),
        migrations.AddField(
            model_name='formacao',
            name='competencias',
            field=models.ManyToManyField(related_name='formacoes', to='portfolio.competencia'),
        ),
    ]
