# Generated by Django 6.0.3 on 2026-04-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_rename_competencia_projeto_competencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciatura',
            name='empresas_parceiras',
            field=models.ManyToManyField(related_name='licenciaturas', to='portfolio.empresaparceira'),
        ),
        migrations.AddField(
            model_name='tfc',
            name='tecnologias',
            field=models.ManyToManyField(related_name='tfcs', to='portfolio.tecnologia'),
        ),
    ]
