# Generated by Django 6.0.3 on 2026-04-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_licenciatura_empresas_parceiras_tfc_tecnologias'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciatura',
            name='objetivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='url_curso',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='objetivos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
