# Generated by Django 6.0.3 on 2026-04-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_licenciatura_objetivos_licenciatura_url_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='docentes/'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='pagina_pessoal',
            field=models.URLField(blank=True, null=True),
        ),
    ]
