# Generated by Django 6.0.3 on 2026-04-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_docente_email_alter_docente_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatura',
            name='empresas_parceiras',
            field=models.ManyToManyField(blank=True, related_name='licenciaturas', to='portfolio.empresaparceira'),
        ),
        migrations.RemoveField(
            model_name='unidadecurricular',
            name='licenciatura',
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='licenciatura',
            field=models.ManyToManyField(related_name='ucs', to='portfolio.licenciatura'),
        ),
    ]
