# Generated by Django 6.0.3 on 2026-04-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_licenciatura_empresas_parceiras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makingof',
            name='competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makingofs', to='portfolio.competencia'),
        ),
        migrations.AddField(
            model_name='makingof',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makingofs', to='portfolio.docente'),
        ),
        migrations.AddField(
            model_name='makingof',
            name='empresa_parceira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makingofs', to='portfolio.empresaparceira'),
        ),
        migrations.AddField(
            model_name='makingof',
            name='formacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makingofs', to='portfolio.formacao'),
        ),
        migrations.AddField(
            model_name='makingof',
            name='licenciatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makingofs', to='portfolio.licenciatura'),
        ),
        migrations.AddField(
            model_name='makingof',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makingofs', to='portfolio.projeto'),
        ),
        migrations.AddField(
            model_name='makingof',
            name='tecnologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makingofs', to='portfolio.tecnologia'),
        ),
        migrations.AddField(
            model_name='makingof',
            name='tfc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makingofs', to='portfolio.tfc'),
        ),
        migrations.AddField(
            model_name='makingof',
            name='unidade_curricular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makingofs', to='portfolio.unidadecurricular'),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='empresas_parceiras',
            field=models.ManyToManyField(blank=True, null=True, related_name='licenciaturas', to='portfolio.empresaparceira'),
        ),
    ]
