# Generated by Django 6.0.3 on 2026-04-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_makingof_competencia_makingof_docente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makingof',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='makingof',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='makingof',
            name='empresa_parceira',
        ),
        migrations.RemoveField(
            model_name='makingof',
            name='formacao',
        ),
        migrations.RemoveField(
            model_name='makingof',
            name='licenciatura',
        ),
        migrations.RemoveField(
            model_name='makingof',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='makingof',
            name='tecnologia',
        ),
        migrations.RemoveField(
            model_name='makingof',
            name='tfc',
        ),
        migrations.RemoveField(
            model_name='makingof',
            name='unidade_curricular',
        ),
    ]
