# Generated by Django 6.0.5 on 2026-05-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='titulo',
            field=models.TextField(max_length=200),
        ),
    ]
