# Generated by Django 6.0.5 on 2026-05-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_tfc_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='titulo',
            field=models.TextField(),
        ),
    ]
