# Generated by Django 6.0.5 on 2026-05-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_tfc_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='autor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='curso',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='orientador',
            field=models.TextField(),
        ),
    ]
